### ISSUE TITLE
Bug: Out of memory exception when reading old files

### ISSUE THREAD

**Issue by JakeGonder** [KiARC/Sobriety#15]
There seems to be an issue when updating the app, and then reading a save file created in the old version.

Steps to reproduce:
1 Checkout [version 3.0.0](https://github.com/KiARC/Sobriety/commit/7e9ca9ad8c0c2d76335f6fc39a51bcc9b90d3fb8)
2 Add a couple of entries
3 Checkout the newest version => update the app => start the app => app crashes with this error:

```
java.lang.OutOfMemoryError: OutOfMemoryError thrown while trying to throw OutOfMemoryError; no stack trace available
```

Re-installing the app fixes this bug but also gets rid of previous entries.

**Comment by JakeGonder** [comment]
I spotted a potential cause:
https://github.com/KiARC/Sobriety/blob/1129ac02780d832d3987c830df9a9fe970fcad66/app/src/main/java/com/katiearose/sobriety/Main.kt#L193
you probably didn't intend to recursively call readCache again, but to call readLegacyCache instead?

**Comment by KiARC** [comment]
Ah darn, I know what caused that too. My autoformatter likes to replace deprecated calls with non-deprecated ones and that's meant to be the call to readCacheLegacy

**Comment by JakeGonder** [comment]
I only spotted it via the little "recursive call" indicator, that Android Studio put to it, next to the line number
![grafik](https://user-images.githubusercontent.com/51212295/160209572-77335d58-eb34-42db-bd19-67957015e1d2.png)

**Comment by KiARC** [comment]
Oh that's what that is ahaha

**Comment by KiARC** [comment]
Alright, I've fixed this. The fix will be out in the next patch.
