### ISSUE TITLE
IzzyOnDroid icon links to bigger image instead of app

### ISSUE THREAD

**Issue by pod5tr45** [KiARC/Sobriety#2]
Basically the title. Just FYI, your IzzyOnDroid icon links to a bigger image instead of Izzy's repo.

https://apt.izzysoft.de/fdroid/index/apk/com.katiearose.sobriety

**Comment by KiARC** [comment]
Yeah I'm aware, I never got around to adding the link to it.

**Comment by KiARC** [comment]
Fixed it, thanks for the poke haha

**Comment by pod5tr45** [comment]
Awesome, and thanks for the app. It fills a nice niche in FOSS apps in general. I can't wait to see how it comes along.
