### ISSUE TITLE
Visual tweaks

### ISSUE THREAD

**Issue by JakeGonder** [KiARC/Sobriety#20]
1 Theme inconsistency: Currently the dark theme does have a title bar showing the app name, the light theme does not have one.

2 Improvement idea: Don't show text parts containing 0's.
   E.g. for a new entry, don't show 0 days 0 hours etc, initially just show the seconds.

3 Bug or feature? Its currently possible to set a date / time in the future, which then results in a negative time counting up.

**Comment by KiARC** [comment]
Implementing #3 right now, for a future version

**Comment by KiARC** [comment]
Finished up by @unbiaseduser
