### ISSUE TITLE
stop\restart option over relapse

### ISSUE THREAD

**Issue by nutpantz** [KiARC/Sobriety#25]
Many people stop for a length of time rather then a one time relapse. Then they restart abstaining from whatever. It would be nice if that was an option over just a relapse button that restarts automatically.
Maybe keep time since abstaining was stopped.
I personally would feel better if i could restart a fresh new abstaining attempt from an existing button if i have stopped for a few days, where i would likely trash the last attempt over use the relapse button when i wanted to try abstaining again

**Comment by KiARC** [comment]
That's a great idea. I might add an extra button for "stop" alongside the existing "reset" option, and when you press it it'll essentially display "Stopped" where the time would be and then you can press it again to "Resume" or "Continue" maybe? Is that what you mean?

**Comment by nutpantz** [comment]
Not so much continue since stopping means you have to start over again from day one.
Right now reset starts you over right now 
So if you stop on Monday and don't plan to restart until Friday there is no way to show you have stopped but plan to try again.
I think you only really need stop and start of you want to keep it simple

**Comment by KiARC** [comment]
Ah I see. So kinda like what I was saying before except starting from 0 instead of from where you left it?

**Comment by nutpantz** [comment]
That's right.
