### ISSUE TITLE
history information

### ISSUE THREAD

**Issue by nutpantz** [KiARC/Sobriety#26]
Having a simple history of abstaining from something would be nice. Even more so if you implement the stop\restart idea.

**Comment by KiARC** [comment]
I think I kinda get what you mean, but can you elaborate to clarify?

**Comment by nutpantz** [comment]
Just a history of start and stop times and how long you abstained, By days and hoursb should be enough for most.

So after your stopped abstaining for an addiction you could look at the history of that addiction of your attempts or progress improvement.
