### ISSUE TITLE
addiction list doubles

### ISSUE THREAD

**Issue by nutpantz** [KiARC/Sobriety#27]
I used to have one thing in my addiction list
(Fresh new install from fdroid today) and a half hour later when i looked again the list has doubled to two duplicate addictions..

This happened a few times

I recently added another item to my list and only a few minutes later the list has doubled again to 4 items both items both duplicated.

**Comment by KiARC** [comment]
What in the... I genuinely don't know what could cause that, I'll test for that behavior when I'm able to

**Comment by nutpantz** [comment]
Just wanted to report back that it has added 2 more. So now i have 6 since the last time i looked. So it may not be doubleing and may be just duplication of the original 2  for the 3rd time

**Comment by KiARC** [comment]
Hey I just wanna ask what device you're on, and what Android version. I've been using it myself for a while and haven't noticed that at all and I'm kinda confused. I'm not sure how that could be happening.

**Comment by nutpantz** [comment]
Pixel 6 Android 12l

**Comment by KiARC** [comment]
Huh, I'm on the 6 Pro on the same version so I would expect to see the same thing... I'm sorry I genuinely don't know what's up, I'll look over the code again but it might be on your end

**Comment by nutpantz** [comment]
I'll reset it after the next update and see what happens

**Comment by nutpantz** [comment]
It's doing it on Android 11 lineage os on my s7.
Might be my quit smoking date in 2006 try one with a date like that

**Comment by KiARC** [comment]
I'm just gonna close this since I have not been able to replicate that behaviour at all. If anyone else sees it, or if I do, I'll reopen this.
