### ISSUE TITLE
minSdk too high

### ISSUE THREAD

**Issue by sadellie** [KiARC/Sobriety#28]
Are there any limitations that make this app incompatible with older Android devices? Can't install it from provided APK files.

I think it can be easily lowered to 21.

https://github.com/KiARC/Sobriety/blob/master/app/build.gradle#L11

**Comment by KiARC** [comment]
I'll look into that

**Comment by KiARC** [comment]
I got it down to 26, which is when `Instant.now()` got added

**Comment by unbiaseduser** [comment]
If anyone of you are reading this
i lowered the min SDK to 21 yesterday via [google magic](https://developer.android.com/studio/write/java8-support?hl=en#library-desugaring)

[here's their source code](https://github.com/google/desugar_jdk_libs)

**Comment by KiARC** [comment]
I saw, super impressive ngl, I would never have thought of that
