### ISSUE TITLE
Contribution guidelines

### ISSUE THREAD

**Issue by JakeGonder** [KiARC/Sobriety#3]
Your ReadMe doesn't mention contribution guidelines, so im curious if you are open to PRs.
I think your app is a cool idea so I [forked](https://github.com/JakeGonder/Sobriety/commits/redesign) your project and made some minor changes like adding confirmation dialogs for the delete / reset actions etc.

**Comment by KiARC** [comment]
Ah yeah, my bad. I'm open to PRs haha

**Comment by KiARC** [comment]
I'll check your fork, that sounds like a good update.
