### ISSUE TITLE
Duplicate set of cards created when switching screen orientation

### ISSUE THREAD

**Issue by DePingus** [KiARC/Sobriety#35]
Hi. This is coming along nicely. I found a bug though.

If I turn my phone and it switches from portrait to landscape (or vice versa) with the app open and in the foreground, a duplicate set of fully functional cards will appear. The screen shot below was taken after turning the phone twice (from portrait to landscape, and then back to portrait). So you see two duplicate sets. 

The duplicate cards will disappear if I manually swipe away the app from my recents or force close it from my app settings; Unless I interact with one of the cards by the relapse or delete button. If I do that, all the duplicates become permanent. 

I tested with 1 and then 2 addiction cards. I'm using a OnePlus 8 fully stock running Android 12. 

![Screenshot_2022-10-14-12-58-47-15_282b95c6141e4501442f4489abb6960f](https://user-images.githubusercontent.com/386890/195902879-e8009ecf-ce13-47b5-9cd4-830e8f8cb1b4.jpg)

**Comment by KiARC** [comment]
I've seen many iterations of this bug (happening on app close and open, on swiping between apps, and now on rotation) and this is the first one I've been able to replicate, so thank you so much for letting me know. I'll start working on a fix soon.

Katherine Isabella Andromeda Rose Cofresí

-------- Original Message --------

**Comment by KiARC** [comment]
Solved by @unbiaseduser
