### ISSUE TITLE
Bugs with the "recent average" function?

### ISSUE THREAD

**Issue by unbiaseduser** [KiARC/Sobriety#39]
Afaik the "recent average" function calculates the average of the last 3 abstaining periods. With that in mind, I'd like to report some, uh, weird behavior with it:
- If the addiction has never been relapsed at all, the average displays the time of the current abstaining period. That's kinda odd (and wrong as well), since there's no abstaining history to begin with.
- If it has been relapsed, when you first log the relapse, the average is calculated and displayed correctly. However, when you close the app and open it again, the average displays the time of the new abstaining period.

Example: If I create an addiction with the time of 1 hour ago and I log the relapse, the average is displayed as 20 minutes (which is correct). However, if I close and open the app again, if the time of the new period is 10 seconds, when I open the app, the "average" is displayed as 10 seconds instead of the actual average value.

**Am i gonna fix it?**
- [x] Yes, but only after #38 since i'm not exactly familiar with resolving merge conflicts and stuff. If you know how, plz teach me.

**Comment by KiARC** [comment]
- That is something I need to fix, yeah
- It does? I don't know why that is, I'll have to check

**Comment by KiARC** [comment]
And dw I'm good with merges

**Comment by unbiaseduser** [comment]
Oh, [i actually already fixed it](https://github.com/unbiaseduser/Sobriety/commit/b82ebb81e78445871920e464f3e9b886c7140396). I'll open a PR any second now.
Also, [i added "stop" functionality](https://github.com/unbiaseduser/Sobriety/commit/b844b9283e80d13fc9a40b627345eac19333fdbb) and [history feature](https://github.com/unbiaseduser/Sobriety/commit/9e8f2256ffd02abbfee1111b3a7b47e4e734efb3) as well, maybe you can [try out my branch](https://github.com/unbiaseduser/Sobriety/tree/imdefinitelysober) and give feedback? (Don't mind the README lol, i was just kinda overreacting.)

**Comment by KiARC** [comment]
Thank you for everything you're doing for the project, I'm so sorry I can't keep up, I have a lot going on, but I really hope that I'm not coming off as lazy or uninvolved, I really do care about this project. I'm struggling with school right now so I haven't had a lot of time to work on Sobriety, and every time I'm almost done with something you've already finished it, so I've just started deferring to you. Again, sorry for being slow, but I promise I'm trying my best here. I'll merge your PR soon, whenever I'm between classes and have a moment, hopefully today.
