### ISSUE TITLE
Crashes on launch

### ISSUE THREAD

**Issue by VenterArmand** [KiARC/Sobriety#48]
Ulefone armor 7

**Comment by KiARC** [comment]
Clear the app's storage, it's a cache issue

**Comment by KiARC** [comment]
The solution is to delete the cache, but yes, please try not to break it, I implemented the new cache format so that it could properly detect what things are missing in fill them with 0s

**Comment by unbiaseduser** [comment]
Don't worry, from the next version onwards I'll make the data 100% compatible.
Actually, I've already done it:
`fun fromCacheable(map: HashMap<Int, Any>): Addiction {`
            `//Migration strategies`
            `if (map.size == 7) { //is it version 6.1.1?`
                `return Addiction(`
                    `map[0] as String,`
                    `map[1] as Instant,`
                    `map[2] as Boolean,`
                    `map[3] as Long,`
                    `map[4] as LinkedHashMap<Long, Long>,`
                    `map[5] as Priority,`
                    `//default values...`
                    `LinkedHashMap(),`
                    `LocalTime.of(0, 0),`
                    `LinkedHashMap(),`
                    `map[6] as CircularBuffer<Long>`
                `)`
            `} else return Addiction(`
                `map[0] as String,`
                `map[1] as Instant,`
                `map[2] as Boolean,`
                `map[3] as Long,`
                `map[4] as LinkedHashMap<Long, Long>,`
                `map[5] as Priority,`
                `map[6] as LinkedHashMap<LocalDate, String>,`
                `map[7] as LocalTime,`
                `map[8] as LinkedHashMap<String, Pair<Double, String>>,`
                `map[9] as CircularBuffer<Long>`
            `)`
        `}`

**Comment by KiARC** [comment]
What if instead of just checking the size of it, it assumed that the values were in order (i.e. 1 is always gonna be 1 in every future version)

**Comment by unbiaseduser** [comment]
I'm pretty sure the values are always in order.
Try this code snippet: (it's a map using integer keys with keys inserted sequentially (0, 1, 2, 3, so on.) just like the app's)
`val map = HashMap<Int, String>()`
            `for (i in 0..100) {`
                `map[i] = i.toString()`
            `}`
            `println(map)`
It actually preserves the insertion order every time.
