### ISSUE TITLE
Lengths of time dont match calendar dates

### ISSUE THREAD

**Issue by Taxit0m** [KiARC/Sobriety#58]
Does this app follow the calendar year or does it just accumulate seconds and minutes to form weeks and months?  The app says im 11 months 3 weeks, but by the calendar im 1 year 4 days?

**Comment by KiARC** [comment]
It doesn't follow the calendar year, a month is just 31 days if memory serves. This might change eventually but I don't see it happening soon. Until then this expected behavior and won't be considered a but.

**Comment by Taxit0m** [comment]
Thanks for responding, but i don't see this as a very accurate situation or way to calculate a length of time.  Not all months have 31 days, not all years have 365 days.  If this is expected behavior and not seen as a bug, then you should leave the length of time abstained displayed in hours and not try to calculate days, weeks, months, or years from that because (admitted by you) its displaying incorrect information.  If you dont see this as a problem, and have no intentions of fixing it, its not just that i wouldn't reccomend this app to any user, i would actually recommend they not use this software and use one that displays correct lengths of time.

**Comment by KiARC** [comment]
If it's that important I'll find a way to get it to work, I don't have access to my development machine and likely won't for around a week but I'll put it on my to-do list

**Comment by KiARC** [comment]
I saw the other post you made and removed it because rather than contribute to the conversation you posted it in you chose to insult me and Quang, after I already told you I would fix the bug you so despise. Please refrain from posting off topic responses to issues. If you want to post about this issue, this thread is open for it.

**Comment by Taxit0m** [comment]
Uhm, well i actually started looking for another outlet once you initially stated it was expected behavior because "a month is just 31 days if memory serves" and started adding my input into on a topic labeled feature request where a user asked for this view of length of abstinence.  Nowhere in that post did i insult you, i just stated that using this app or choosing to further develop was moot if for every year of abstinence your app displays it as roughly minus 12 days off and according to you that's normal....  So doing the math if i abstain from alcohol for 5 years your app will tell me "no, you're not 5 years sober, but you will be in about 2 months" which is 60 days (12 days off for each of the 5 calendar years being 12x5=60).   Then you decide to reopen the issue and say ok fine, i guess if its that big of a deal ill fix it, but you wont have access to a device capable of editing the code for about a week.  (the one you're on doesn't have a text editor?  You're joking right?  You're giving me the piss for a laugh!). 
   
  Now i will insult you ok, this is an insult.  If your memory is not serving you well enough to be able to remember the months of the year, and not all of them contain exactly 31 days... I have no idea which substances you're tracking abstinence from, but it sounds some pretty heavy stuff, and you should probably go press the relapse button....

**Comment by KiARC** [comment]
Honey, I don't think every month is 31 days, I said that in reference to the code which is programmed that way as a way to make it less complicated. I'm sending messages here from a phone so I can't exactly work on the app very easily, and you're going to have to be patient until I can access my laptop, the charger for which is broken (and I'm waiting for a replacement for it). I'm developing this app for free, on my own time, you have no right to demand things of me like this or insult my intelligence based on a simple abstraction.
