### ISSUE TITLE
Recent Average is inaccurate for the first few relapses

### ISSUE THREAD

**Issue by cubandle** [KiARC/Sobriety#62]
Since the recent average is calculated from the last 3 relapses, it is inaccurate when there are less than 3 relapses in the timeline.

To reproduce:
1. Create an addition that starts several months ago (in my case, I tested with 11 months and 3 weeks)
3. Immediately relapse. Average will display the time period divided by 3 (~4 months)
4. Relapse 2 more times, noting that the average barely changes.

**Comment by KiARC** [comment]
Yeah I might need to fix that 😅 thanks for letting me know
