### ISSUE TITLE
8.0.0 update crashes on open

### ISSUE THREAD

**Issue by avaaum** [KiARC/Sobriety#68]
v8.0.0 update crashes immediately upon opening on Pixel 6 Pro running Graphene OS

**Comment by KiARC** [comment]
Clear app data, it's a cache bug I forgot to fix, it'll be fixed next release

**Comment by avaaum** [comment]
wasn't fixed. still persists

**Comment by KiARC** [comment]
It is fixed. The fix is not backwards compatible, but for example updating from v9.0.0 to the next version will no longer have this bug
