### ISSUE TITLE
Average sober time 

### ISSUE THREAD

**Issue by CactiChameleon9** [KiARC/Sobriety#8]
I think it would be useful to log how long you were sober for and display an average (possibly of the last 3 resets) meaning users could aim for more (or less) time sober from something

**Comment by KiARC** [comment]
Ahhh that's a good idea.

**Comment by KiARC** [comment]
Closed, see #9

**Comment by CactiChameleon9** [comment]
Woah, that was quick. Nice one

**Comment by KiARC** [comment]
Haha I mean it wasn't too difficult to throw together and it was a really great idea ^^
