### ISSUE TITLE
Cleanup of Addiction class

### ISSUE THREAD

**Issue by cubandle** [KiARC/Sobriety#89]
Now that we have a flexible deserializer, I was thinking to refactor the Addiction class. Rather than needing to use isStopped and isFuture(), what do you think about a state system using an enum? Also, lastRelapse and timeStopped are both already found in the history, so maybe they can be converted to functions. The exception to this is that lastRelapse stores future start times before they are added into history, but this can be changed. Lastly, I think we can remove the relapses CircularBuffer since we calculate averages in a different way now.

To keep these changes consistent with past versions, the deserializer will:
- ignore `timeStopped` and `relapses`
- Use `lastRelapse` to calculate if isFuture() and otherwise discard the value
- Use `isStopped` to translate into the status enum.

Summary:
Remove `lastRelapse`, `isStopped`, `timeStopped`, `relapses`
Add `status` enum  `{Ongoing, Stopped, Future}`

Let me know if this is reasonable.

**Comment by KiARC** [comment]
Good ideas!
