### ISSUE TITLE
Bug: Miscalculation by one day

### ISSUE THREAD

**Issue by MeirKlemp** [KiARC/Sobriety#97]
Hi, I recently started using your app to stop my addiction. Thank you for developing the app.

 I found out that sometimes the time since last relapse is one day more than the real value.

How to reproduce the bug:
1. Create a new addiction with time later than now.
2. Go to the addictions list and look at the time since relapse of the added addiction.

Version v10.0.0

Screenshots:
![Screenshot_20230210-091646(1).png](https://user-images.githubusercontent.com/50945641/218028876-7b50164e-8276-46a6-b912-2259631eb7cd.png)
![Screenshot_20230210-091707.png](https://user-images.githubusercontent.com/50945641/218028963-065fa8cc-ff06-45a3-9adc-cc5c4d42f500.png)
![Screenshot_20230210-091719.png](https://user-images.githubusercontent.com/50945641/218029000-ef17a358-3d6d-4631-9577-4db8cbf935bd.png)

**Comment by MeirKlemp** [comment]
The bug is in this function: https://github.com/KiARC/Sobriety/blob/dd65f74bfa36e09c18eab0ca880f1b20ebc6f5ee/app/src/main/java/com/katiearose/sobriety/utils/Utils.kt#L63

If  for example, a day passed but not 24 hours since the start of the addiction, then the `Period` will say that a day passed, even though it didn't.

I have written a fix:
```kotlin
val durationToEndDay = Duration.between(startDate, startDate.toLocalDate().plusDays(1).atStartOfDay(ZoneOffset.UTC))
val d = if (durationToEndDay >= duration) (period.days % 7) else (period.days % 7 - 1)
```
Notice that `ZoneOffset.UTC` should be updated according to the local ZoneOffset.

**Comment by cubandle** [comment]
Sorry about that, the patch for this issue is in process in a PR [here](https://github.com/KiARC/Sobriety/pull/96) ([last commit](https://github.com/KiARC/Sobriety/pull/96/commits/7b2d97aab9475e403c75b3d629c56ada52d5130e) specificially)
